module.exports.kick = function (message, bot) {
    if (testDroits("mod", message) && userPresent(message)) {

        // check si le bot a la permision mod pour kicker
        if (!message.guild.member(bot.user).roles.find("name", "mod")) {
            return message.reply("le bot n'a pas la permision mod");
        }

        // retourne le premier user nommer dans la commande
        var user = message.mentions.users.first();

        // regarde si le user les bien présent dans le server
        if (!user) {
            return message.reply("L'user n'est pas valide");
        }

        //kick enfin le premier user qui a été citer dans la commande kick,
        // envoie mesage de confirmation ou bien renvoie l'erreur. Le catch(console.error) ne marche qu'avec les commandes discord.js
        // message.guild.member(message.mentions.users.first()).kick().then(member => { -> version antérieur au cas ou ça foire
        message.guild.member(user).kick().then(member => {
            message.channel.send('Kicked!' + member.user.username);
        }).catch(console.error);
    }
};

function testDroits(drois, message) {
    var modRole = message.guild.roles.find("name", drois);

    if (!message.member.roles.has(modRole.id)) {
        console.log(message.mentions.users.size);
        message.reply("le drois " + drois + " est nécessaire");
        return false;
    } else {
        return true;
    }

} // test si la persone ayant lancer la comande à les droits nécessaires

function userPresent(message) {
    if (message.mentions.users.size === 0) {
        message.reply("merci de citer un utilisateur");

        return false;
    } else {
        return true;
    }
} // test si un utilisateur est citer dans la comande
